export const ERC20_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
];

export const NBT_TOKEN_ABI = [
  ...ERC20_ABI,
  "function getFeeConfig() view returns (uint256 _buyFee, uint256 _sellFee, address _feeReceiver)",
  "function isExcludedFromFee(address) view returns (bool)",
  "function burn(uint256 amount)",
  "function nonces(address owner) view returns (uint256)",
  "function DOMAIN_SEPARATOR() view returns (bytes32)",
];

export const STAKING_BANK_ABI = [
  "function stakingToken() view returns (address)",
  "function rewardToken() view returns (address)",
  "function interactionFeeToken() view returns (address)",
  "function totalStaked() view returns (uint256)",
  "function totalRankDistributed() view returns (uint256)",
  "function totalRankClaimed() view returns (uint256)",
  "function totalInviteRewardsAccrued() view returns (uint256)",
  "function totalInviteRewardsClaimed() view returns (uint256)",
  "function interactionFee() view returns (uint256)",
  "function inviteReward() view returns (uint256)",
  "function minReferralStakeValue() view returns (uint256)",
  "function stakeValueRate() view returns (uint256)",
  "function LOCK_PERIOD() view returns (uint256)",
  "function startTime() view returns (uint256)",
  "function currentEpochId() view returns (uint256)",
  "function pendingCarryover() view returns (uint256)",
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function feeReceiver() view returns (address)",
  "function priceFeed() view returns (address)",
  "function operators(address) view returns (bool)",
  "function paused() view returns (bool)",
  "function userInfo(address) view returns (uint256 totalStaked, uint256 totalWithdrawn, uint256 stakeCount, uint256 activeStakeCount, address referrer, uint256 directReferrals, uint256 referralStakeVolume, uint256 personalStakeVolume, uint256 pendingInviteRewards, uint256 totalInviteClaimed, uint256 lockedInviteRewards, uint256 inviteUnlockCursor)",
  "function stakeRecords(address user, uint256 stakeId) view returns (uint256 amount, uint256 scoreValue, uint256 startTime, bool active, bool countedToReferrer)",
  "function epochRank(uint256 epochId, address node) view returns (uint256)",
  "function qualifiedReferral(address referrer, address user) view returns (bool)",
  "function getUserInfo(address user) view returns (tuple(uint256 totalStaked, uint256 totalWithdrawn, uint256 stakeCount, uint256 activeStakeCount, address referrer, uint256 directReferrals, uint256 referralStakeVolume, uint256 personalStakeVolume, uint256 pendingInviteRewards, uint256 totalInviteClaimed, uint256 lockedInviteRewards, uint256 inviteUnlockCursor) info, uint256 pendingRewards, uint256 totalClaimed, uint256 rank)",
  "function getUserStakes(address user) view returns (uint256[] stakeIds, uint256[] amounts, uint256[] scoreValues, uint256[] startTimes, bool[] actives)",
  "function getStakeRecord(address user, uint256 stakeId) view returns (uint256 amount, uint256 scoreValue, uint256 startTime, bool active)",
  "function getInviteRewardLocks(address referrer) view returns (address[] invitees, uint256[] stakeIds, uint256[] amounts, uint256[] unlockTimes, uint256 cursor)",
  "function pendingRewardAll(address user) view returns (uint256)",
  "function getMiningStatus() view returns (uint256 _totalStaked, uint256 _totalDistributed, uint256 _claimableRewards, bool _releaseInProgress, uint256 _startTime, uint256 _rankedNodeCount)",
  "function getInteractionFeeConfig() view returns (address feeToken, uint256 fee, address receiverA, address receiverB)",
  "function getCurrentRelease() view returns (uint256 epochId, uint256 poolAmount, uint256 totalNodes, uint256 totalClaimed, uint256 claimStart, uint256 claimEnd, bool settled, bool disabled)",
  "function getEpoch(uint256 epochId) view returns (tuple(address node, uint256 personalScore, uint256 inviteScore, uint256 totalScore)[] nodes, uint256 snapshotTime, uint256 poolAmount, uint256 totalClaimed, uint256 totalNodes, bool settled, bool disabled)",
  "function pendingEpochReward(uint256 epochId, address node) view returns (uint256)",
  "function getRankClaimed(address user) view returns (uint256)",
  "function getNodeRank(address node) view returns (uint256)",
  "function getRankedNodeCount() view returns (uint256)",
  "function getRankedNodes(uint256 offset, uint256 limit) view returns (address[] nodes, uint256[] scores, uint256 total)",
  "function getRankRewardPreview(uint256 amount, uint256 totalNodes, uint256 rank) view returns (uint256)",
  "function getReferrals(address user) view returns (address[])",
  "function getReferralsPaginated(address user, uint256 offset, uint256 limit) view returns (address[] result, uint256 total)",
  "function hasReferrer(address user) view returns (bool)",
  "function hasClaimed(uint256 epochId, address node) view returns (bool)",
  "function getReinvestPreview(address user) view returns (uint256 inviteAmount, uint256 rankAmount, uint256 principalAmount, uint256 totalAmount, uint256 maturedStakeCount)",
  "function stake(uint256 amount, address referrer) payable",
  "function withdraw(uint256 stakeId) payable",
  "function setReferrer(address referrer) payable",
  "function claimNodeRewards() payable",
  "function reinvest(address referrer)",
  "function claimEpochReward() payable",
  "function claimEpochReward(uint256 epochId) payable",
  "function openEpoch()",
  "function fundEpoch(uint256 amount)",
  "function settleEpoch()",
  "function setInteractionFeeConfig(address feeToken, uint256 fee, address receiver)",
  "function setInviteReward(uint256 reward)",
  "function setMinReferralStakeValue(uint256 value)",
  "function setStakeValueRate(uint256 rate)",
  "function setPriceFeed(address feed)",
  "function setOperator(address operator, bool status)",
  "function pause()",
  "function unpause()",
  "function recoverWrongToken(address token, address to, uint256 amount)",
  "function transferOwnership(address newOwner)",
  "function acceptOwnership()",
  "event Deposit(address indexed user, address indexed referrer, uint256 indexed stakeId, uint256 amount)",
  "event Withdraw(address indexed user, uint256 indexed stakeId, uint256 amount)",
  "event ReferrerSet(address indexed user, address indexed referrer)",
  "event ReferralQualified(address indexed referrer, address indexed user, uint256 inviteReward)",
  "event InviteRewardUnlocked(address indexed referrer, address indexed invitee, uint256 amount)",
  "event NodeScoreUpdated(address indexed node, uint256 score)",
  "event NodeRewardsClaimed(address indexed user, uint256 inviteReward, uint256 rankReward)",
  "event NodeRewardsCompounded(address indexed user, uint256 indexed stakeId, uint256 amount)",
  "event EpochOpened(uint256 indexed epochId, uint256 totalNodes, uint256 carryover, bool disabled)",
  "event EpochFunded(uint256 indexed epochId, address indexed funder, uint256 amount, uint256 poolAmount)",
  "event EpochRewardClaimed(uint256 indexed epochId, address indexed node, uint256 rank, uint256 amount)",
  "event EpochSettled(uint256 indexed epochId, uint256 claimed, uint256 carryover)",
  "event InteractionFeeConfigUpdated(address indexed feeToken, uint256 fee, address indexed receiver)",
  "event InteractionFeePaid(address indexed user, address indexed token, uint256 totalFee, address indexed receiver)",
  "event InviteRewardUpdated(uint256 reward)",
  "event MinReferralStakeValueUpdated(uint256 value)",
  "event StakeValueRateUpdated(uint256 rate)",
  "event OperatorUpdated(address indexed operator, bool status)",
  "event PriceFeedUpdated(address indexed priceFeed)",
  "event Paused()",
  "event Unpaused()",
  "event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event WrongTokenRecovered(address indexed token, address indexed to, uint256 amount)",
];

// 旧版 V1 质押合约 ABI（主网 0x903f...），仅供旧项目数据迁移参考，CON 项目不使用
// 注意：实际链上合约返回字段数与文档 ABI 不同，这里以链上实际为准（4 words feeConfig / 16 words getUserInfo）
export const LEGACY_STAKING_BANK_ABI = [
  "function stakingToken() view returns (address)",
  "function rewardToken() view returns (address)",
  "function paused() view returns (bool)",
  "function pendingRewardAll(address user) view returns (uint256)",
  "function getMiningStatus() view returns (uint256 _totalStaked, uint256 _totalDistributed, uint256 _claimableRewards, bool _releaseInProgress, uint256 _startTime, uint256 _rankedNodeCount)",
  "function getInteractionFeeConfig() view returns (address feeToken, uint256 fee, address receiverA)",
  "function getUserInfo(address user) view returns (uint256 totalStaked, uint256 totalWithdrawn, uint256 stakeCount, uint256 activeStakeCount, address referrer, uint256 directReferrals, uint256 referralStakeVolume, uint256 pendingInviteRewards, uint256 totalInviteClaimed, uint256 pendingRankRewards, uint256 totalRankClaimed, uint256 lockedInviteRewards, uint256 inviteUnlockCursor, uint256 pendingRewards, uint256 totalClaimed, uint256 rank)",
  "function getUserStakes(address user) view returns (uint256[] stakeIds, uint256[] amounts, uint256[] scoreValues, uint256[] startTimes, bool[] actives)",
  "function getNodeRank(address node) view returns (uint256)",
  "function currentEpochId() view returns (uint256)",
  "function totalRankDistributed() view returns (uint256)",
  "function totalRankClaimed() view returns (uint256)",
  "function totalInviteRewardsAccrued() view returns (uint256)",
  "function totalInviteRewardsClaimed() view returns (uint256)",
  "function claimNodeRewards() payable",
  "function claimReferralRewards() payable",
  "function claimAll() payable",
  "function withdraw(uint256 stakeId) payable",
];
